accel-pppd/radius/acct.c, accel-pppd/radius/req.c
if Delegated-IPv6-Prefix was received in Access-Accept message, it is necessary to send it in radacct Start message
=> Send Delegated-IPv6-Prefix attribute in Accounting-Start message

accel-pppd/cli/telnet.c
small check for zero buffer length on load history
=> cli/telnet: fix crash on damaged history file.

accel-pppd/cli/std_cmd.c
The addition of this feature will allow you to remotely recognize the version of the accel-pppd via cli or telnet, it will also be possible to monitor the version with monitoring systems such as Zabbix
Task in phabricator
[https://phabricator.accel-ppp.org/T40](https://phabricator.accel-ppp.org/T40)
```
> accel-cmd help
show stat - shows various statistics information
show version - shows version of running accel-pppd
......
> accel-cmd show version
1.12.0-126-g3b74e10
```
=> cli: T40: Show version of running accel-pppd from cli or telnet

accel-pppd/CMakeLists.txt, accel-pppd/cli/show_sessions.c, accel-pppd/ifcfg.c, accel-pppd/include/ap_net.h, accel-pppd/include/ap_session.h, accel-pppd/net.c, accel-pppd/radius/attr_defs.h, accel-pppd/radius/dict/dictionary, accel-pppd/radius/dict/dictionary.accel, accel-pppd/radius/dm_coa.c, accel-pppd/radius/radius.c, accel-pppd/session.c, config.h.in
Added Accel-VRF-Name attribute vendor Accel-PPPP
Add possibility to send Access-Accept and CoA messages to set VRF for the user interface.
(Accel-VRF-Name="0") "0" value is used to return the user interface back to default (global routing table)
All VRFs should be manually created in advance, e.g.:
```
ip link add VRF_NAME type vrf table RT_TABLE_ID
ip link set dev VRF_NAME up
```
(Please read https://www.kernel.org/doc/Documentation/networking/vrf.txt )
CoA-message example to assign VRF for user session:
`echo 'User-Name=bob, Accel-VRF-Name="test"' | radclient -x 127.0.0.1:3799 coa testing123`
CoA-message example to remove VRF from user session:
`echo 'User-Name=bob, Accel-VRF-Name="0"' | radclient -x 127.0.0.1:3799 coa testing123`
If Accel-VRF-Name is used in Access-Accept message, but …
=> vrf: T10: Add VRF support

accel-pppd/accel-ppp.conf, accel-pppd/accel-ppp.conf.5, accel-pppd/libnetlink/libnetlink.c, accel-pppd/net.c
Netlink buffers may overflow so it might be useful to increase send and receive 
netlink buffer sizes.
Two parameters to [common] configuration section added: nl-rcv-buffer,
nl-snd-buffer.
It is required to set (sysctl) net.core.wmem_max>=nl-snd-buffer and 
net.core.rmem_max>=nl-rcv-buffer before running accel-pppd
To check current netlink buffer size and related info use the following command:
% ss -f netlink -m 
0 0 rtnl:kernel * skmem:(r0,rb212992,t0,tb212992,f0,w0,o0,bl0,d0)
0 0 rtnl:-1140221812 * skmem:(r0,rb2048000,t0,tb80000,f0,w0,o0,bl0,d0)
0 0 rtnl:accel-pppd/14285 * skmem:(r0,rb2048000,t0,tb65536,f0,w0,o0,bl0,d0)
...
(Please check man ss to get the meaning for r,rb,t,tb,f,w,o,bl and d params)
In the ss output you will see the values doubled from configured.
First accel-pppd …
=> T55: add netlink buffer size configuration parameters

accel-pppd/accel-ppp.conf.5, accel-pppd/radius/dm_coa.c, accel-pppd/radius/radius.c, accel-pppd/radius/radius.h, accel-pppd/radius/radius_p.h, accel-pppd/radius/req.c, accel-pppd/radius/serv.c
New configuration format:
```
[radius]
server=address,secret[,auth-port=1812][,acct-port=1813][,vrf=VRF_NAME][,req-limit=0][,fail-timeout=0,max-fail=0,][,weight=1][,backup]
dae-server=x.x.x.x:port,secret[,vrf=VRF_NAME]
```
By default, VRF name is undefined.
=> Added support for binding device name for radius request and DM/CoA server. 

accel-pppd/radius/dict.c, accel-pppd/radius/packet.c
This patch fixes buffer overflow if radius packet contains invalid atribute length
and attrubute type from the following list: ipv4addr, ipv6addr or ifid
Reported-by: Chloe Ong
Reported-by: Eugene Lim <spaceraccoon@users.noreply.github.com>
Signed-off-by: Sergey V. Lobanov <sergey@lobanov.in>
=> fix buffer overflow when receive radius packet

accel-pppd/accel-ppp.conf, accel-pppd/accel-ppp.conf.5, accel-pppd/radius/radius.c, accel-pppd/radius/radius_p.h, accel-pppd/radius/req.c
This patch introduces nas-port-id-in-req switch to disable sending
NAS-Port-Id attribute in radauth and radacct messages. New switch
might be useful if radius server cannot properly handle this
attrubite.
Signed-off-by: Sergey V. Lobanov <sergey@lobanov.in>
=> add switch to disable sending NAS-Port-Id

drivers/ipoe/ipoe.c
This patch fixes a compile error on linux kernel >= 5.15
In kernel 5.15, data type of `netdev->dev_addr` has been changed to `const unsigned char*` 
The new helper method `dev_addr_mod` must be used to set the value instead of setting directly by `memcpy`.
=> Use helper method to set ipoe device function

accel-pppd/ipv6/dhcpv6.c, accel-pppd/ipv6/nd.c
The ipv6 configuration via accel-ppp does not go as expected when the link ends in a given namespace (other than the default) because the ipv6 socket is always created in the default namespace. 
This pr fix ipv6 socket creation for these 2 modules : ipv6_nd and ipv6_dhcp, when link is terminated inside netns. I tested 671c54b on the current master branch (also in the version also 2.11) and it's work as i expected but i don't test the commit 26270ec for the moment(in progress).
CPE, COLLECT and ROUTER run on linux distribution (network oriented) based on debian.
I simulate this network infrastructure :  CPE --pppoe-- COLLECT--l2tp-- ROUTER
*Freeradius configuration on the ROUTER*
<pre>
site1@client1.telco Cleartext-Password := 'passl2tp', Auth-Type := Accept
Framed-IP-Address = …
=> Fix ipv6 inside netns

accel-cmd/accel_cmd.c
MacOS socket does not support SOCK_CLOEXEC. This patch uses fcntl
with FD_CLOEXEC instead of using SOCK_CLOEXEC in socket() call
Signed-off-by: Sergey V. Lobanov <sergey@lobanov.in>
=> accel-cmd: add macos compatibility

.github/workflows/build-and-run.yml, cmake/cpack.cmake
This PR includes two commits:
1. build: add deb packaging support for Ubuntu 22.04 and Debian 12
2. ci: add build jobs (Github CI)
First commit is required for the second one.
Full description is in the second commit (ci: add build jobs (Github CI))
CI run results (artifacts & logs) can be reviewed here:  https://github.com/svlobanov/accel-ppp/actions/runs/2968158823 (CI run results will be removed after 90 days by github)
=> ci: add build jobs (Github CI) 

.github/workflows/run-tests.yml, tests/.gitignore, tests/README.md, tests/accel-cmd/test_cmd_basic.py, tests/accel-cmd/test_real_commands.py, tests/accel-pppd/ipoe/conftest.py, tests/accel-pppd/ipoe/dhcpv4/test_ipoe_shared_session_wo_auth.py, tests/accel-pppd/ipoe/test_ipoe_driver.py, tests/accel-pppd/pppoe/conftest.py, tests/accel-pppd/pppoe/test_pppoe_disc.py, tests/accel-pppd/pppoe/test_pppoe_pado_delay.py, tests/accel-pppd/pppoe/test_pppoe_session_wo_auth.py, tests/accel-pppd/pppoe/test_pppoe_vlan_mon.py, tests/accel-pppd/test_basic.py, tests/accel-pppd/test_vlan_mon_driver.py, tests/common/accel_pppd_process.py, tests/common/config.py, tests/common/dhclient_process.py, tests/common/iface.py, tests/common/netns.py, tests/common/pppd_process.py, tests/common/process.py, tests/common/veth.py, tests/common/vlan.py, tests/conftest.py, tests/gcovr.conf
This is a proposal for test system.
Running log and coverage report is here: https://github.com/svlobanov/accel-ppp/actions/runs/2995929181 (will be saved for 90 days, then it will be removed by github)
=================================================
This commit adds tests (using python3 pytest framework):
1. Test basic accel-cmd commands (show version, show stat, etc)
2. Test ipoe shared session up (dhcpv4) without radius
3. Test pppoe discovery (without PADO delay)
4. Test pppoe discovery (without PADO delay)
5. Test pppoe session up (ipv4) without radius
6. Test vlan creation using vlan-mon (pppoe)
These tests require external utils. Please read tests/README.md how to setup
environment, how to run the tests and how to generate coverage report
Also, run-tests.yml contains step-by-step …
=> add tests and ci workflow for running tests

accel-pppd/ctrl/ipoe/dhcpv4.c
The DHCP Notify Packet send out for the load balancing mechanism (weight) is lacking a DHCP End Option (255). For accel-ppp this is not an issue, since the only consumer of this packet should be other accel-ppp Hosts.
Our Ruckus ICX Switches try to parse these packets with activated DHCP Snooping function resulting in some critical errors on the Switch CLI:
`DHCP Option82: WARNING: No END OPTION found before bounds.`
So this looks really bad and fixing is easy by adding the DHCP Option 255 end marker.
=> Add missing dhcp end option on dhcp notify packet

accel-pppd/ctrl/ipoe/dhcpv4.c, accel-pppd/ctrl/ipoe/dhcpv4.h, accel-pppd/ctrl/pppoe/pppoe.c, accel-pppd/ctrl/sstp/sstp.c, accel-pppd/ipv6/dhcpv6.c
Hi @svlobanov! Sorry for the delayed response.
I had to recreate the pull request as the last one would not display my updates.
A more detailed description of what is going on will be on the phabricator.
```
- IPoE/DHCP4: Specify minimal, suitable alignment explicitly. 
We need to guarantee 2-byte alignment for the `hdr` pointer in
`ip_csum(uint16_t *buf)` calculation
- PPPOE: Suppress false-positive warning for `sockaddr_pppox`.
Similar issue: https://github.com/kernelslacker/trinity/pull/40
- Introduce tmp variables to avoid alignment issues for SSTP/DHCPv6
For additional details:
https://phabricator.accel-ppp.org/T72
Signed-off-by: Volodymyr Huti <v.huti@vyos.io>
```
Although, I still need to do some testing on some real setups.
It would be great if somebody could help or provide some …
=> T72: Fix compilations warnings for unaligned variable access

accel-pppd/cli/show_sessions.c, accel-pppd/ctrl/sstp/sstp.c, accel-pppd/extra/pppd_compat.c, accel-pppd/include/ap_session.h, accel-pppd/libnetlink/iputils.c, accel-pppd/libnetlink/iputils.h, accel-pppd/lua/session.c, accel-pppd/ppp/ppp_lcp.c, accel-pppd/ppp/ppp_lcp.h, accel-pppd/radius/acct.c, accel-pppd/session.c
This patch-set has two changes:
1. Use 64-bit interface statistics directly from the kernel instead of doing custom 32-bit overflow checking.
When a link has a relatively high throughput, the 32-bit packet and byte counters could overflow multiple times between accounting runs.
To accommodate this limitation, directly use 64-bit interface statistics.
This also gets rid of the internal giga-word counters.
2. Add PACKETS_SENT and PACKETS_RCVD to the pppd-compat environment.
=> Use 64-bit interface statistics and some more env parameters for pppd-compat

cmake/cpack.cmake
This includes CentOS Stream, AlmaLinux, and RockyLinux.
=> Add support for building RPMs on RHEL 9 clones

.github/workflows/build-and-run.yml, .github/workflows/run-tests.yml
Ubuntu 18.04 is EOL so remove it from CI
Debian12 python requires --break-system-packages  to install pip3 packages from root user
=> ci: remove Ubuntu 18.04 from CI pipelines, fix python issue for Debian12

accel-pppd/libnetlink/iputils.c
Fix a segmentation fault when starting when accel-ppp is configured with an non vlan interface.
=> libnetlink: fix a crash with a non vlan interface

accel-pppd/ctrl/ipoe/ipoe.c
Link-selection pointer is not set to NULL when link-selection IPOE option is not set. It results in a memory access violation in dhcpv4_packet_insert_opt82()
Set link-selection pointer to NULL if unset to fix the issue.
Fixes: 61e31c591e ("ipoe: add dhcp link selection sub-option")
=> ipoe: fix memory access violation with unset link-selection

.github/workflows/build-and-run.yml, .github/workflows/run-tests.yml
This PR has two ci improvements:
1. build for mainline kernel - it allows to check accel-ppp build on latest kernels (including -rc kernels)
2. debian13 is trixie so explicit name is used in ci job to avoid using debian unstable
=> ci: build for mainline kernel, use explicit name for debian13 instead of sid

accel-pppd/extra/chap-secrets.c, accel-pppd/extra/ippool.c
In case of invalid configuration we might get stack overflow with unexpected consequences.
=> Add safeguards to parse_gw_ip_address helper functions

.github/workflows/run-tests.yml
This patch fixes debian10 build
=> ci: remove unnecessary gcovr python package where it's not required

accel-pppd/logs/log_tcp.c
Discovered using clang sanitizers.
=> log_tcp: Fix small memory leak

README, accel-pppd/accel-ppp.conf.5, accel-pppd/shaper/limiter.c, accel-pppd/shaper/shaper.c, accel-pppd/shaper/shaper.h
Use the following configuration to enable clsact up and down limiters:
[shaper]
up-limiter=police
down-limiter=clsact
It is also recommended to set down-burst-factor=1.0
How to check current configuration in Linux:
tc qdisc show dev ppp0
tc filter show dev ppp0 egress
tc filter show dev ppp0 ingress
=> shaper: add clsact policer support

accel-pppd/CMakeLists.txt
On Gentoo __free_fn_t wont be detected properly without this include.
Reported-by: Stanislav <stasn77@gmail.com>
Author: Stanislav <stasn77@gmail.com>
=> CMakeLists.txt: gentoo fix for __free_fn_t detection

accel-pppd/accel-ppp.conf.5, accel-pppd/ipv6/dhcpv6.c, accel-pppd/ipv6/dhcpv6.h, accel-pppd/ipv6/dhcpv6_packet.c
While trying to implement a DS-Lite setup with accel-ppp as a PPPoE concentrator, I ran into the issue where my CPE would request the AFTR gateway hostname via DHCPv6 Option 64, but accel-ppp was unable to send it. 
I added an extra configuration parameter `aftr-gw` to the `ipv6-dhcp` section. 
I also added proper code to handle the option when printing out DHCPv6 packets in verbose mode.
=> ipv6_dhcp: Add RFC6334 AFTR-Name option support

.github/workflows/build-and-run.yml, .github/workflows/run-tests.yml
Debian10 LTS is EoL (ref: https://wiki.debian.org/LTS) so it is removed from CI.
Debian10 ELTS is maintained by third-party organization, only some packages are maintained so there is no reason to support Debian10 in CI
=> ci: remove debian10 support

accel-pppd/ctrl/sstp/sstp.c, accel-pppd/triton/triton.c
This patch intends to fix HTTP mode neither returns 404 nor redirects to other URLs (as well as other statuses but 200 for SSTP). Discussed in #124. Also it removes define for log_debug2 function in Triton lib to make it actually log Triton events.
=> Fixes the issue #124 "HTTP replay for non SSTP query" and log_debug2 in Triton lib

.github/workflows/run-tests.yml
github now allows kvm and cpu passthrough, enable it to speedup ci
speedup is about x4-x5
=> ci: speedup virtual machines using kvm and host cpu passthrough

.github/workflows/run-tests.yml, accel-pppd/CMakeLists.txt, accel-pppd/accel-ppp.conf, accel-pppd/extra/logwtmp.c, tests/accel-pppd/general/test_basic.py, tests/accel-pppd/general/test_pcre_negative_cases.py, tests/accel-pppd/ipoe/dhcpv4/test_ipoe_shared_session_wo_auth.py, tests/accel-pppd/pppoe/conftest.py, tests/accel-pppd/pppoe/test_pppoe_disc.py, tests/accel-pppd/pppoe/test_pppoe_pado_delay.py, tests/accel-pppd/pppoe/test_pppoe_session_wo_auth.py, tests/accel-pppd/pppoe/test_pppoe_vlan_mon.py
Alpine Linux uses musl libc so now accel-ppp is tested under musl
Currently, Alpine Linux doesn't provide a link to the latest stable version so direct link to Alpine 3.20 is used
Improved musl support might be used to run on platforms like openwrt without additional patches
=> ci: run tests in alpine vm

accel-pppd/session.c
This patch allows to build accel-ppp on mips32/ppc32 openwrt (musl)
=> fix __WORDSIZE macro on musl 32 bit platforms

accel-pppd/ctrl/pppoe/CMakeLists.txt
Tested on Entware. Now it is possible to use chap-secrets authentication with pppoe. Refer to the linked issue for info.
Closes: #189
=> pppoe: fix #189

tests/accel-pppd/pppoe/test_pppoe_session_chap_secrets.py, tests/conftest.py
This PR should be merged after https://github.com/accel-ppp/accel-ppp/pull/190 that fixes radius.so issue on musl libc distros
=> tests: add test pppoe session using chap-secrets auth

accel-pppd/ctrl/pppoe/CMakeLists.txt
This reverts commit 543700aed1ac045f12dfafd898bbbbae955fee31 (PR #190) .
=> Revert "Fix #189: Make module pppoe work without module radius"

accel-pppd/ctrl/l2tp/l2tp.c
It is logical, that function should remain same, not changed to free.
=> fix(musl/l2tp_session_free): Fix, likely typo

accel-pppd/ppp/ppp_lcp.c
Closes #204
The size of the LCP Echo-Reply is determined by selecting the minimum between  the Echo-Request size, and the client's MRU.  
Re-using the example of the issue #204 , this allows to have Request - Reply of this kind, complying with RFC1171:
```
PPPoE  [ses 0x2fc0] LCP (0xc021), length 1494: LCP, Echo-Request (0x09), id 0, length 1494
PPPoE  [ses 0x2fc0] LCP (0xc021), length 1482: LCP, Echo-Reply (0x0a), id 0, length 1482
```
=> fix(ppp_lcp): truncate echo reply if size > client MRU

accel-pppd/ctrl/ipoe/dhcpv4.c, accel-pppd/ctrl/ipoe/ipoe.c, accel-pppd/ctrl/l2tp/l2tp.c, accel-pppd/ctrl/l2tp/packet.c, accel-pppd/ctrl/pptp/pptp.c, accel-pppd/logs/log_tcp.c, accel-pppd/radius/packet.c
This patch fixes compile errors on GCC 14 like the following
```
/root/accel-ppp/accel-pppd/radius/packet.c: In function 'rad_packet_recv': /root/accel-ppp/accel-pppd/radius/packet.c:142:72: error: passing argument 5 of 'recvfrom' from incompatible pointer type [-Wincompatible-pointer-types]
142 |                         n = recvfrom(fd, pack->buf, REQ_LENGTH_MAX, 0, addr, &addr_len);
|                                                                        ^~~~
|                                                                        |
|                                                                        struct sockaddr_in *
In file included from /usr/include/netinet/in.h:10,
from /usr/include/arpa/inet.h:9,
from /root/accel-ppp/accel-pppd/radius/packet.c:10: …
```
=> build: fix compile errors on GCC 14

accel-pppd/extra/pppd_compat.c
This PR adds support for the Framed-Interface-Id attribute for radattr in the pppd_compat module.
=> pppd_compat: add Framed-Interface-Id attribute support in radattr

accel-pppd/CMakeLists.txt
Linux kernel before 4.11 has the issue decribed in the commit: https://github.com/torvalds/linux/commit/2618be7dccf8739b89e1906b64bd8d551af351e6
It fails accel-ppp build on entware. Let's include sys/socket.h to avoid this issue. All files that use linux/if_arp.h includes sys/socket.h before
Related to https://github.com/orgs/accel-ppp/discussions/187
=> build: fix build for entware (HAVE_GOOD_IFARP detection issue)

.github/workflows/run-tests-bigendian.yml
s390x is the only big-endian platform supported by major Linux vendors. Alpine s390x is the only major distro that includes pppoe kernel module. Ubuntu, Debian, RHEL (and Fedora) removed pppoe from kernel config so alpine s390x is used. Alpine doesn't provide cloud-image for s390x that is why netboot installed is used.
It is almost zero probability that someone will run accel-ppp on s390x IBM mainframe, but testing on big-endian platform is useful for another platforms (e.g. mips-be and ppc-be which is still in use on home gateways and supported by openwrt).
----
This PR should be merged after https://github.com/accel-ppp/accel-ppp/pull/179 and https://github.com/accel-ppp/accel-ppp/pull/181
=> ci: run tests on alpine s390x (big-endian)

accel-pppd/ctrl/pptp/pptp.c
I think the error handling code of `post_msg` is wrongly implemented due to coding typo. The `EPIPE` should be also considered and then return -1, just like `PPTP_write`: 
https://github.com/accel-ppp/accel-ppp/blob/1b8711cf75a7c278d99840112bc7a396398e0205/accel-pppd/ctrl/pptp/pptp.c#L539-L570
This pr fix https://github.com/xebd/accel-ppp/issues/158
=> Fix post_msg implementation bug

.github/workflows/run-tests.yml, tests/accel-pppd/ipoe/dhcpv4/test_ipoe_shared_session_chap_secrets.py, tests/accel-pppd/ipoe/dhcpv4/test_ipoe_shared_session_lua_chap_secrets.py, tests/accel-pppd/pppoe/test_pppoe_session_chap_secrets.py, tests/conftest.py
radius and chap-secrets can't work together due to musl library limiations
This patch disables chap-secrets related tests on alpine
ref: https://github.com/accel-ppp/accel-ppp/pull/190#issuecomment-2331036461
=> tests,ci: disable chap-secrets related tests on alpine

.github/workflows/build-and-run.yml
Building in ubuntu:devel container might help to find the issues related to newest kernels and other software updates
=> ci: add build in ubuntu:devel container

drivers/ipoe/ipoe.c
Closes: https://github.com/accel-ppp/accel-ppp/issues/217
Ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=05c1280a2bcfca187fe7fa90bb240602cf54af0a
Ref: https://github.com/torvalds/linux/commit/05c1280a2bcfca187fe7fa90bb240602cf54af0a
Reported-By: https://github.com/axe-kenig
CI run for kernel 6.12 (alpine edge): https://github.com/svlobanov/accel-ppp/actions/runs/12100376477/job/33738894243?pr=22
=> ipoe: fix driver for kernel 6.12 (NETIF_F_NETNS_LOCAL)

accel-pppd/ctrl/ipoe/dhcpv4_options.c
Allowed using multiple NTP servers in DHCP option 42
=> ipoe: fixed DHCP option 42 (ntp servers)

.github/workflows/build-and-run.yml, .github/workflows/run-tests.yml
This tests failing now with following message:
```
This is a scheduled Ubuntu 20.04 retirement.
Ubuntu 20.04 LTS runner will be removed on 2025-04-15.
For more details, see https://github.com/actions/runner-images/issues/11101
```
=> (workflows): Ubuntu 20.04 is deprecated, removing it

CMakeLists.txt, accel-pppd/ctrl/pppoe/CMakeLists.txt
This commit introduces the ability to detect if the project is being built with the MUSL C library.
A new variable `MUSL` is set to `ON` if MUSL is detected, and `OFF` otherwise. This is achieved by checking the output of `ldd --version`.
The `accel-pppd/ctrl/pppoe/CMakeLists.txt` file is updated to conditionally link the `connlimit` library only when building with MUSL.
=> feat(build): Add MUSL detection and conditional linking
